USE master;
GO

IF NOT EXISTS (SELECT 1 FROM sys.fn_helpcollations()
               WHERE name = N'Serbian_Cyrillic_100_CI_AS')
    THROW 50001, N'Колација Serbian_Cyrillic_100_CI_AS није доступна на овој инстанци.', 1;
GO

IF DB_ID(N'BugTracker') IS NOT NULL
BEGIN
    ALTER DATABASE [BugTracker] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE [BugTracker];
END
GO

CREATE DATABASE [BugTracker] COLLATE Serbian_Cyrillic_100_CI_AS;
GO

ALTER DATABASE [BugTracker] SET RECOVERY SIMPLE;
GO

USE [BugTracker];
GO

CREATE SCHEMA impl    AUTHORIZATION dbo;
GO
CREATE SCHEMA spec    AUTHORIZATION dbo;
GO
CREATE SCHEMA api_dev AUTHORIZATION dbo;
GO
CREATE SCHEMA api_qa  AUTHORIZATION dbo;
GO

USE master;
GO
IF SUSER_ID(N'AppLoginDEV') IS NOT NULL DROP LOGIN AppLoginDEV;
IF SUSER_ID(N'AppLoginQA')  IS NOT NULL DROP LOGIN AppLoginQA;
GO

CREATE LOGIN AppLoginDEV WITH PASSWORD = N'Prp#Dev2026!', CHECK_POLICY = OFF, DEFAULT_DATABASE = [BugTracker];
CREATE LOGIN AppLoginQA  WITH PASSWORD = N'Prp#Qa2026!',  CHECK_POLICY = OFF, DEFAULT_DATABASE = [BugTracker];
GO

USE [BugTracker];
GO
CREATE USER AppUserDEV FOR LOGIN AppLoginDEV WITH DEFAULT_SCHEMA = api_dev;
CREATE USER AppUserQA  FOR LOGIN AppLoginQA  WITH DEFAULT_SCHEMA = api_qa;
GO

CREATE APPLICATION ROLE DataProviderDEV WITH PASSWORD = N'Prp#RoleDev2026!', DEFAULT_SCHEMA = api_dev;
CREATE APPLICATION ROLE DataProviderQA  WITH PASSWORD = N'Prp#RoleQa2026!',  DEFAULT_SCHEMA = api_qa;
GO
