USE [BugTracker];
GO

GRANT SELECT, EXECUTE, VIEW DEFINITION ON SCHEMA::api_dev TO DataProviderDEV;
GRANT SELECT, EXECUTE, VIEW DEFINITION ON SCHEMA::api_qa  TO DataProviderQA;
GO

DENY SELECT, INSERT, UPDATE, DELETE, EXECUTE ON SCHEMA::impl    TO DataProviderDEV;
DENY SELECT, INSERT, UPDATE, DELETE, EXECUTE ON SCHEMA::spec    TO DataProviderDEV;
DENY SELECT, EXECUTE                         ON SCHEMA::api_qa  TO DataProviderDEV;

DENY SELECT, INSERT, UPDATE, DELETE, EXECUTE ON SCHEMA::impl    TO DataProviderQA;
DENY SELECT, INSERT, UPDATE, DELETE, EXECUTE ON SCHEMA::spec    TO DataProviderQA;
DENY SELECT, EXECUTE                         ON SCHEMA::api_dev TO DataProviderQA;
GO

GRANT CONNECT TO AppUserDEV;
GRANT CONNECT TO AppUserQA;
GO

DENY SELECT, INSERT, UPDATE, DELETE, EXECUTE ON SCHEMA::impl    TO AppUserDEV, AppUserQA;
DENY SELECT, INSERT, UPDATE, DELETE, EXECUTE ON SCHEMA::spec    TO AppUserDEV, AppUserQA;
DENY SELECT, EXECUTE ON SCHEMA::api_dev TO AppUserDEV, AppUserQA;
DENY SELECT, EXECUTE ON SCHEMA::api_qa  TO AppUserDEV, AppUserQA;
GO
